/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Medidas;

import general.seeText;
import javax.swing.JOptionPane;

/**
 *
 * @author josue
 */
public class interfazNoAgrupados extends javax.swing.JFrame {

    Cola cola;
    seeText formula = new seeText();

    public interfazNoAgrupados() {
        initComponents();
        jButton2.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNum = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cbEstado = new javax.swing.JComboBox<>();
        cbActividad = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtShowValor = new javax.swing.JTextArea();
        txtShowForm = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtDeci = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumKeyReleased(evt);
            }
        });
        getContentPane().add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 78, -1));

        jButton1.setText("insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jButton2.setText("Reiniciar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "muestra", "poblacion" }));
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        cbActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "media", "mediana", "moda", "varianza", "desviacion estandar", "coeficiente de variacion", "percentil" }));
        cbActividad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbActividadMouseReleased(evt);
            }
        });
        cbActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActividadActionPerformed(evt);
            }
        });
        cbActividad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbActividadKeyReleased(evt);
            }
        });
        getContentPane().add(cbActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        txtShowValor.setColumns(20);
        txtShowValor.setRows(5);
        jScrollPane1.setViewportView(txtShowValor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 296, 60));
        getContentPane().add(txtShowForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 137, 740, 235));

        jButton3.setText("eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtDeci.setText("3");
        getContentPane().add(txtDeci, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabel1.setText("decimales");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));
        getContentPane().add(txtCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 70, -1));

        jButton4.setText("ingresar n veces");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jButton5.setText("ingresa datos de arriba");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cola = new Cola(100);
        cola.setEstado((String) cbEstado.getSelectedItem());
        cola.setDecimales(Integer.parseInt(txtDeci.getText()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double numero = Double.parseDouble(txtNum.getText());
        cola.adicionar(numero);
        txtNum.requestFocus();
        txtNum.setText("");
        txtShowValor.setText(cola.toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumKeyReleased

    }//GEN-LAST:event_txtNumKeyReleased

    private void cbActividadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbActividadKeyReleased

    }//GEN-LAST:event_cbActividadKeyReleased

    private void cbActividadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbActividadMouseReleased

    }//GEN-LAST:event_cbActividadMouseReleased

    private void cbActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActividadActionPerformed
        switch ((String) cbActividad.getSelectedItem()) {
            case "media":
                txtShowForm.setIcon(formula.getIconLaTex(cola.mostrarMedia()));
                break;
            case "mediana":
                txtShowForm.setIcon(formula.getIconLaTex(cola.mostrarMediana()));
                break;
            case "moda":
                txtShowForm.setIcon(formula.getIconLaTex(cola.mostrarModa()));
                break;
            case "varianza":
                txtShowForm.setIcon(formula.getIconLaTex(cola.mostrarVarianza()));
                break;
            case "desviacion estandar":
                txtShowForm.setIcon(formula.getIconLaTex(cola.mostrarDesviacion()));
                break;
            case "coeficiente de variacion":
                txtShowForm.setIcon(formula.getIconLaTex(cola.mostrarCoeficiente()));
                break;
            case "percentil":
                double percentil = Double.parseDouble(JOptionPane.showInputDialog("poner percentil en porcentaje"));
                txtShowForm.setIcon(formula.getIconLaTex(cola.mostrarPercentil(percentil/100)));
                break;
        }
    }//GEN-LAST:event_cbActividadActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        double numero = Double.parseDouble(txtNum.getText());
        cola.eliminar(numero);
        txtNum.requestFocus();
        txtNum.setText("");
        txtShowValor.setText(cola.toString());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        cola.setEstado((String) cbEstado.getSelectedItem());
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        double numero = Double.parseDouble(txtNum.getText());
        int cantidad = Integer.parseInt(txtCant.getText());
        for (int i = 0; i < cantidad; i++) {
            cola.adicionar(numero);
        }
        txtNum.requestFocus();
        txtNum.setText("");
        txtShowValor.setText(cola.toString());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String[] valores = txtShowValor.getText().split(",");
        for (int i = 0; i < valores.length; i++) {
            cola.adicionar(Double.parseDouble(valores[i]));
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazNoAgrupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazNoAgrupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazNoAgrupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazNoAgrupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazNoAgrupados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbActividad;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtDeci;
    private javax.swing.JTextField txtNum;
    private javax.swing.JLabel txtShowForm;
    private javax.swing.JTextArea txtShowValor;
    // End of variables declaration//GEN-END:variables
}
