/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Medidas;

import general.seeText;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josue
 */
public class interfazAgrupados extends javax.swing.JFrame {

    seeText formula = new seeText();
    Agrupado ag;

    public interfazAgrupados() {
        initComponents();
    }

    public void media() {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        int rows = tabla.getRowCount();
        modelo.setColumnCount(4);
        modelo.addColumn("MCi*fi");
        for (int i = 0; i < rows - 1; i++) {
            double frecuencia = ag.getMcf(i);
            tabla.setValueAt(frecuencia, i, 4);
        }
        tabla.setValueAt(ag.sumaMcfi(), rows - 1, 4);
        txtShowForm.setIcon(formula.getIconLaTex(ag.mostrarMediaAgrupado()));
    }

    public double varianza() {
         DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        int rows = tabla.getRowCount();
        modelo.setColumnCount(4);
        modelo.addColumn("MCi*fi");
        for (int i = 0; i < rows - 1; i++) {
            double frecuencia = ag.getMcf(i);
            tabla.setValueAt(frecuencia, i, 4);
        }
        double sumMcf = ag.sumaMcfi();
        double N = ag.getN();
        tabla.setValueAt(sumMcf, rows - 1, 4);
        double media = sumMcf / N;
        modelo.addColumn("(mc-X)^2");
        modelo.addColumn("(mc-X)^2 *f");
        double acum = 0;
        for (int i = 0; i < rows - 1; i++) {
            double mc = (double) tabla.getValueAt(i, 2);
            double suma = Math.pow((mc - media), 2);
            tabla.setValueAt(suma, i, 5);
            double frecuencia = ag.getFrecuencia(i);
            double suma2 = suma * frecuencia;
            tabla.setValueAt(suma2, i, 6);
            acum += suma2;
        }
        tabla.setValueAt(acum, rows - 1, 6);
        txtShowForm.setIcon(formula.getIconLaTex(ag.mostrarVarianzaAgrupado(acum)));
        return acum;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtCantInt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtFirst = new javax.swing.JTextField();
        txtSecond = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cbEstado = new javax.swing.JComboBox<>();
        cbActividad = new javax.swing.JComboBox<>();
        txtShowForm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "li :limite inferior", "ls: limite superior", "MC: marca de clase", "fi: frecuencia"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 710, 158));
        getContentPane().add(txtCantInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 41, -1));

        jButton1.setText("crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));
        getContentPane().add(txtFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 60, -1));
        getContentPane().add(txtSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 50, -1));

        jLabel1.setText("cant intervalor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 110, 20));

        jLabel2.setText("ultimo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, 20));

        jLabel3.setText("valor: primero");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jButton2.setText("send frecu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "muestra", "poblacion" }));
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        cbActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "media", "mediana", "moda", "varianza", "desviacion estandar", "coeficiente de variacion", "percentil" }));
        cbActividad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbActividadMouseReleased(evt);
            }
        });
        cbActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActividadActionPerformed(evt);
            }
        });
        cbActividad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbActividadKeyReleased(evt);
            }
        });
        getContentPane().add(cbActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));
        getContentPane().add(txtShowForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 740, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel dt = (DefaultTableModel) tabla.getModel();
        int cantIntervalo = Integer.parseInt(txtCantInt.getText());
        dt.setRowCount(cantIntervalo + 1);
        ag = new Agrupado(cantIntervalo, (String) cbEstado.getSelectedItem());
        double inicio = Double.parseDouble(txtFirst.getText());
        double ultimo = Double.parseDouble(txtSecond.getText());
        int amplitud = (int) Math.floor((ultimo - inicio) / cantIntervalo);
        for (int i = 0; i < cantIntervalo; i++) {
            double limitederecho = amplitud + inicio;
            double marcaClase = (limitederecho + inicio) / 2;
            ag.setLimiteInferior(inicio, i);
            ag.setLimiteSuperior(limitederecho, i);
            tabla.setValueAt(inicio, i, 0);
            tabla.setValueAt(limitederecho, i, 1);
            tabla.setValueAt(marcaClase, i, 2);
            inicio = limitederecho;
        }
        dt.setColumnCount(4);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int rows = tabla.getRowCount();
        for (int i = 0; i < rows - 1; i++) {
            double frecuencia = Double.parseDouble((String) tabla.getValueAt(i, 3));
            ag.setFrecuencia(frecuencia, i);
        }
        tabla.setValueAt(ag.getN(), rows - 1, 3);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        ag.setEstado((String) cbEstado.getSelectedItem());
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void cbActividadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbActividadMouseReleased

    }//GEN-LAST:event_cbActividadMouseReleased

    private void cbActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActividadActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        int rows = tabla.getRowCount();
        modelo.setColumnCount(4);
        switch ((String) cbActividad.getSelectedItem()) {
            case "media":
                media();
                break;
            case "mediana":
                modelo.addColumn("F: frecuencia acumulada");
                double acumulado = 0;
                for (int i = 0; i < rows - 1; i++) {
                    acumulado += ag.getFrecuencia(i);
                    tabla.setValueAt(acumulado, i, 4);
                }
                txtShowForm.setIcon(formula.getIconLaTex(ag.mostrarMedianaAgrupado()));
                break;
            case "moda":
                txtShowForm.setIcon(formula.getIconLaTex(ag.mostrarModaAgrupado()));
                break;
            case "varianza":
                varianza();
                break;
            case "desviacion estandar":
                txtShowForm.setIcon(formula.getIconLaTex(ag.mostrarDesviacionAgrupado(varianza())));
                break;
            case "coeficiente de variacion":
                txtShowForm.setIcon(formula.getIconLaTex(ag.mostrarCoeficienteAgrupado(varianza())));
                break;
            case "percentil":
                modelo.addColumn("F: frecuencia acumulada");
                double acum = 0;
                for (int i = 0; i < rows - 1; i++) {
                    acum += ag.getFrecuencia(i);
                    tabla.setValueAt(acum, i, 4);
                }
                double percentil = Double.parseDouble(JOptionPane.showInputDialog("poner percentil en porcentaje"));
                txtShowForm.setIcon(formula.getIconLaTex(ag.mostrarPercentilAgrupado(percentil / 100)));
                break;
        }
    }//GEN-LAST:event_cbActividadActionPerformed

    private void cbActividadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbActividadKeyReleased

    }//GEN-LAST:event_cbActividadKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazAgrupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazAgrupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazAgrupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazAgrupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazAgrupados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbActividad;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCantInt;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtSecond;
    private javax.swing.JLabel txtShowForm;
    // End of variables declaration//GEN-END:variables
}
