package intervalo;

import general.seeText;


public class interfaz extends javax.swing.JFrame {

    intervalo intervalo;
    public interfaz() {
        initComponents();
        this.formula = new seeText();
    }
seeText formula;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        IPoblacion = new javax.swing.JTextField();
        TeditEntrada = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        I1 = new javax.swing.JTextField();
        I2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        Idecimales = new javax.swing.JTextField();
        Idesconfianza = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Tedit1 = new javax.swing.JLabel();
        Itabla1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Tedit2 = new javax.swing.JLabel();
        Itabla2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        TeditResul = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuantitativa","Cualitativa","Varianza" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));
        getContentPane().add(IPoblacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 40, -1));

        TeditEntrada.setText("ingresar: ");
        getContentPane().add(TeditEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 180, 20));

        jLabel1.setText("Poblaciones 1 | 2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jButton1.setText("Enviar Valor: ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));
        getContentPane().add(I1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 60, -1));

        I2.setEnabled(false);
        getContentPane().add(I2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 60, -1));

        jLabel2.setText("B");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 10, -1));

        jLabel3.setText("A");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jCheckBox1.setText("Varianza poblacional conocida");
        jCheckBox1.setEnabled(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 90));

        jLabel8.setText("cantidad de decimales");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        Idecimales.setText("4");
        getContentPane().add(Idecimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 40, -1));

        Idesconfianza.setText("0.05");
        Idesconfianza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdesconfianzaActionPerformed(evt);
            }
        });
        getContentPane().add(Idesconfianza, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 50, -1));

        jLabel7.setText("a = ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 30, -1));

        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));
        getContentPane().add(Tedit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 220, 30));

        Itabla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Itabla1ActionPerformed(evt);
            }
        });
        getContentPane().add(Itabla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 70, -1));

        jButton3.setText("Enviar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));
        getContentPane().add(Tedit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 230, 30));

        Itabla2.setEnabled(false);
        Itabla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Itabla2ActionPerformed(evt);
            }
        });
        getContentPane().add(Itabla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 70, -1));

        jButton4.setText("Resolver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, -1, -1));
        getContentPane().add(TeditResul, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 690, 170));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 330, 50));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("=DISTR.NORM.ESTAND.INV(a); solo 3 digitos\n//devolder valor fuera de la tabla\n=INV.T(a;gl): solo 4 decimales\n=INV.CHICUAD(a;gl): solo 3 decimales\n=INV.F(a;gl1;gl2): solo 2 decimales\n=F.inv(a,gl1,gl2); solo 2 decimales\nAl terminar:\nCon un nivel de desconfianza de a%, \nel intervalo de .... es de valor1, valor2.\n++ u1 > u2\n- - u1 < u2\n- + u1=u2; la diferencia de medias son iguales");
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 280, 150));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("Nota al cliente:\nPara un eficiente servicio, te consejamos:\nSi aparece un o^2, escribirlo con normalidad\nsi aparece un numero tipo: 15.0\n no poner el decimal sobrante.\nalguna duda preguntar a tu coordinador");
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 280, 340, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String tipo = (String) jComboBox1.getSelectedItem();
        jTextArea1.setText("");
        int poblacion = Integer.parseInt(IPoblacion.getText());
        if(tipo == "Cuantitativa"){
            jCheckBox1.setEnabled(true);
        }else{
            jCheckBox1.setEnabled(false);
        }
        if(poblacion==2) I2.setEnabled(true);
        else I2.setEnabled(false);
        intervalo = new intervalo(poblacion,tipo);
        intervalo.llenarEntradas();
        TeditEntrada.setText("Ingresar:    " + intervalo.getEntradas()[0]);
        if(poblacion==2) {
            jTextArea1.setText("(A)\t(B)\n");
        }else{
            jTextArea1.setText(intervalo.getEntradas()[0]);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int n = intervalo.getN();
        int inicio = intervalo.getInicio() +1;

        if(inicio < n){

            int poblacion = intervalo.getPoblaciones();
            if(poblacion==2)
            intervalo.llenar2(Double.parseDouble(I2.getText()));
            intervalo.llenar1(Double.parseDouble(I1.getText()));
            if(poblacion==2) {
                jTextArea1.append(intervalo.getEntradas()[inicio] +"=" +intervalo.getValor1(inicio)+ "\t");
                jTextArea1.append(intervalo.getEntradas()[inicio] +"=" +intervalo.getValor2(inicio) + "\n");
            }else {
                jTextArea1.append("=" + intervalo.getValor1(inicio));
                if(inicio < n-1){
                    jTextArea1.append("\n" + intervalo.getEntradas()[inicio+1]);
                }
            }
            if(inicio < n-1){
                TeditEntrada.setText("Ingresar:      " + intervalo.getEntradas()[inicio+1]);
            }
            I1.setText("");
            I2.setText("");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        intervalo.setVarianzaPobCo((jCheckBox1.isSelected()));
        intervalo.llenarEntradas();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void IdesconfianzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdesconfianzaActionPerformed

    }//GEN-LAST:event_IdesconfianzaActionPerformed

    private void Itabla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Itabla1ActionPerformed
     
    }//GEN-LAST:event_Itabla1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        intervalo.setTabla();
        intervalo.setDecimales(Integer.parseInt(Idecimales.getText()));
        intervalo.setDesconfianza(Double.parseDouble(Idesconfianza.getText()));     
        String tipo = intervalo.getTipo();
        Tedit1.setIcon(formula.getIconLaTex(intervalo.getTablaFormula(true),15));
        if(tipo=="Varianza"){
            Itabla2.setEnabled(true);            
            Tedit2.setIcon(formula.getIconLaTex(intervalo.getTablaFormula(false),20));      
        }else{
             Itabla2.setEnabled(false);
             Tedit2.setIcon(null);  
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String tipo = intervalo.getTipo();
        intervalo.setValorTabla(Double.parseDouble(Itabla1.getText()));
        if(tipo=="Varianza" ){
            intervalo.setValorTabla2(Double.parseDouble(Itabla2.getText()));
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Itabla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Itabla2ActionPerformed
        
    }//GEN-LAST:event_Itabla2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TeditResul.setIcon(formula.getIconLaTex(intervalo.getFormulaText(),25));
        String tipo = intervalo.getTipo();
        int poblaciones = intervalo.getPoblaciones();
        boolean varianzaPobCo = intervalo.isVarianzaPobCo();
        if(tipo=="Cuantitativa" && poblaciones == 2 && varianzaPobCo==false)            
            jLabel9.setIcon(formula.getIconLaTex(intervalo.spCuadradoText(),20));
        else jLabel9.setIcon(null); 
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField I1;
    private javax.swing.JTextField I2;
    private javax.swing.JTextField IPoblacion;
    private javax.swing.JTextField Idecimales;
    private javax.swing.JTextField Idesconfianza;
    private javax.swing.JTextField Itabla1;
    private javax.swing.JTextField Itabla2;
    private javax.swing.JLabel Tedit1;
    private javax.swing.JLabel Tedit2;
    private javax.swing.JLabel TeditEntrada;
    private javax.swing.JLabel TeditResul;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
